# .goreleaser.yml
# Configuration for GoReleaser. See https://goreleaser.com/intro/ for documentation.

# Project name (should match your binary name)
project_name: tide

# Runs before the build process
before:
  hooks:
    # Ensure dependencies are tidy
    - go mod tidy

# Build configuration
builds:
  - # Main build configuration
    id: tide-build # Build ID
    # Path to main package
    main: ./cmd/tide
    env:
      - CGO_ENABLED=1
    # Target platforms - limited to what we have compilers for
    goos:
      - linux
      - windows # Windows builds with CGO might need special handling
      - darwin # Note: Darwin/macOS builds may require a macOS runner
    goarch:
      - amd64
      - arm64 # Only build ARM64 for Linux
    ignore:
      - goos: windows
        goarch: arm64
      # Disable Darwin builds in cross-compilation as they require a macOS builder
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: amd64
    # Build hooks
    hooks:
      # This is a workaround to use the right compiler for each target
      pre: |
        {{ if eq .Os "linux" }}
        {{ if eq .Arch "arm64" }}
        export CC=aarch64-linux-gnu-gcc
        {{ end }}
        {{ end }}
        {{ if eq .Os "windows" }}
        export CC=x86_64-w64-mingw32-gcc
        {{ end }}
    # Inject version information using ldflags
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.BuildDate={{.Date}} -X main.BuiltBy=goreleaser
    binary: "{{ .ProjectName }}"

# Archive configuration (for .tar.gz and .zip files)
archives:
  - # Default archive settings
    id: tide-archives
    # Name template for archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# NFPM configuration (for DEB and RPM packages)
nfpms:
  - # Configuration for creating DEB and RPM packages
    id: tide-packages
    package_name: tide

    # --- Required metadata ---
    vendor: "Bethropolis"
    homepage: "https://github.com/bethropolis/tide"
    maintainer: "Bethropolis <bethropolis@gmail.com>"
    description: "A terminal text editor written in Go."
    license: "MIT"

    # Formats to generate
    formats:
      - deb
      - rpm

    # Files to include in the package and their destinations
    contents:
      - src: "{{ .Path }}"
        dst: "/usr/bin/{{ .ProjectName }}"
        file_info:
          mode: 0755

# Generate checksums for artifacts
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot configuration (for builds from main/master branch)
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Changelog generation configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

# GitHub Release configuration
release:
  draft: false
  prerelease: auto
  name_template: "Release {{.Tag}}"

