# .goreleaser.yml
# Configuration for GoReleaser. See https://goreleaser.com/intro/ for documentation.

# Project name (should match your binary name)
project_name: tide

# Runs before the build process
before:
  hooks:
    # Ensure dependencies are tidy
    - go mod tidy

# Build configuration - simplified for CGO
builds:
  - # Main build configuration
    id: tide-build 
    main: ./cmd/tide
    env:
      - CGO_ENABLED=1
    # For development builds with --single-target, only build for current platform
    # For release builds, we'll use xgo via the release.yml workflow
    goos:
      - linux
    goarch:
      - amd64
    # No build hooks to avoid the panic
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.BuildDate={{.Date}} -X main.BuiltBy=goreleaser
    binary: "{{ .ProjectName }}"

# Archive configuration (for .tar.gz and .zip files)
archives:
  - # Default archive settings
    id: tide-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# NFPM configuration (for DEB and RPM packages)
nfpms:
  - # Configuration for creating DEB and RPM packages
    id: tide-packages
    package_name: tide

    # --- Required metadata ---
    vendor: "Bethropolis"
    homepage: "https://github.com/bethropolis/tide"
    maintainer: "Bethropolis <bethropolis@gmail.com>"
    description: "A terminal text editor written in Go."
    license: "MIT"

    # Formats to generate
    formats:
      - deb
      - rpm

    # Files to include in the package and their destinations
    contents:
      - src: "{{ .Path }}"
        dst: "/usr/bin/{{ .ProjectName }}"
        file_info:
          mode: 0755

# Generate checksums for artifacts
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot configuration (for builds from main/master branch)
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Changelog generation configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

# GitHub Release configuration
release:
  draft: false
  prerelease: auto
  name_template: "Release {{.Tag}}"

