# .github/workflows/dev.yml
name: Development Build

# Trigger workflow only on pushes to the 'dev' branch
on:
  push:
    branches:
      - dev
    # Also trigger specifically on tag pushes if you want tags pushed directly to trigger a release
    tags:
      - 'v*.*.*' # Optional: if you want pushing tags directly to trigger a release via this workflow

# Permissions needed for GoReleaser to create releases (when tagged)
permissions:
  contents: write

jobs:
  # Job to build development artifacts or releases using GoReleaser
  build_dev_or_release:
    name: Build Dev Artifacts or Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # GoReleaser needs the full history to generate changelogs/snapshot names correctly
          fetch-depth: 0
          fetch-tags: true # Ensure tags are fetched

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21' # Use a version compatible with your project and GoReleaser

      # Optional: Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run GoReleaser (Release on Tag)
        # Run only if the ref triggering the workflow is a tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          # Perform the full release process
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Set CGO_ENABLED=1 if your project requires CGO
          # CGO_ENABLED: "1"

      - name: Run GoReleaser (Build Only - No Tag)
        # Run only if the ref triggering the workflow is NOT a tag (i.e., a branch push)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          # Use 'build' to only generate artifacts in dist/ based on snapshot config
          # Does NOT create a GitHub release/pre-release
          args: build --snapshot --clean
        env:
          # Token might be needed for private repos/dependencies, even if not releasing
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Set CGO_ENABLED=1 if your project requires CGO
          # CGO_ENABLED: "1"

      - name: Upload Build Artifacts (No Tag)
        # Fixed: Run only if the ref triggering the workflow is NOT a tag
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          # Name the artifact uniquely, e.g., using the commit SHA
          name: tide-dev-build-${{ github.sha }}
          # Upload the contents of the 'dist' directory where goreleaser build puts artifacts
          path: dist/
          # Optional: How long to retain the artifact (default is 90 days)
          # retention-days: 7
          if-no-files-found: error # Error if the dist directory is empty